// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    
    
    public class skill : LocalDataBase
    {
        
        private string _Name;
        
        private double _NextLevelID;
        
        private bool _IsPassive;
        
        private System.Collections.Generic.List<double> _Buffs;
        
        private double _AttackNum;
        
        private System.Collections.Generic.List<double> _AttackRatio;
        
        private double _AttackCount;
        
        private string _Icon;
        
        private string _Des;
        
        private string _Effect;
        
        private double _EffectType;
        
        // 技能名
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        // 下一级ID
        public double NextLevelID
        {
            get
            {
                return this._NextLevelID;
            }
            set
            {
                this._NextLevelID = value;
            }
        }
        
        // 是否被动技能
        public bool IsPassive
        {
            get
            {
                return this._IsPassive;
            }
            set
            {
                this._IsPassive = value;
            }
        }
        
        // Buff列表
        public System.Collections.Generic.List<double> Buffs
        {
            get
            {
                return this._Buffs;
            }
            set
            {
                this._Buffs = value;
            }
        }
        
        // 攻击单位
        public double AttackNum
        {
            get
            {
                return this._AttackNum;
            }
            set
            {
                this._AttackNum = value;
            }
        }
        
        // 攻击系数
        public System.Collections.Generic.List<double> AttackRatio
        {
            get
            {
                return this._AttackRatio;
            }
            set
            {
                this._AttackRatio = value;
            }
        }
        
        // 攻击次数
        public double AttackCount
        {
            get
            {
                return this._AttackCount;
            }
            set
            {
                this._AttackCount = value;
            }
        }
        
        // 图标
        public string Icon
        {
            get
            {
                return this._Icon;
            }
            set
            {
                this._Icon = value;
            }
        }
        
        // 技能描述
        public string Des
        {
            get
            {
                return this._Des;
            }
            set
            {
                this._Des = value;
            }
        }
        
        // 特效路径
        public string Effect
        {
            get
            {
                return this._Effect;
            }
            set
            {
                this._Effect = value;
            }
        }
        
        // 特效类型
        public double EffectType
        {
            get
            {
                return this._EffectType;
            }
            set
            {
                this._EffectType = value;
            }
        }
    }
}
