// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    
    
    public class achievetable_SQL : LocalDataBase
    {
        
        private string _AchieveDatil;
        
        private double _Title;
        
        private string _Achieve1;
        
        private string _AchieveCount1;
        
        private string _IconPath;
        
        private double _UnlockType1;
        
        private double _UnlockCount1;
        
        private double _UnlockType2;
        
        private double _UnlockCount2;
        
        private double _UnlockType3;
        
        private double _UnlockCount3;
        
        private double _UnlockType4;
        
        private double _UnlockCount4;
        
        // 成就描述
        public string AchieveDatil
        {
            get
            {
                return this._AchieveDatil;
            }
            set
            {
                this._AchieveDatil = value;
            }
        }
        
        // 称号
        public double Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this._Title = value;
            }
        }
        
        // 成就物品1(结果)
        public string Achieve1
        {
            get
            {
                return this._Achieve1;
            }
            set
            {
                this._Achieve1 = value;
            }
        }
        
        // 成就数量1
        public string AchieveCount1
        {
            get
            {
                return this._AchieveCount1;
            }
            set
            {
                this._AchieveCount1 = value;
            }
        }
        
        // 图片路径
        public string IconPath
        {
            get
            {
                return this._IconPath;
            }
            set
            {
                this._IconPath = value;
            }
        }
        
        // 解锁材料1
        public double UnlockType1
        {
            get
            {
                return this._UnlockType1;
            }
            set
            {
                this._UnlockType1 = value;
            }
        }
        
        // 解锁数量1
        public double UnlockCount1
        {
            get
            {
                return this._UnlockCount1;
            }
            set
            {
                this._UnlockCount1 = value;
            }
        }
        
        // 解锁材料2
        public double UnlockType2
        {
            get
            {
                return this._UnlockType2;
            }
            set
            {
                this._UnlockType2 = value;
            }
        }
        
        // 解锁数量2
        public double UnlockCount2
        {
            get
            {
                return this._UnlockCount2;
            }
            set
            {
                this._UnlockCount2 = value;
            }
        }
        
        // 解锁材料3
        public double UnlockType3
        {
            get
            {
                return this._UnlockType3;
            }
            set
            {
                this._UnlockType3 = value;
            }
        }
        
        // 解锁数量3
        public double UnlockCount3
        {
            get
            {
                return this._UnlockCount3;
            }
            set
            {
                this._UnlockCount3 = value;
            }
        }
        
        // 解锁材料4
        public double UnlockType4
        {
            get
            {
                return this._UnlockType4;
            }
            set
            {
                this._UnlockType4 = value;
            }
        }
        
        // 解锁数量4
        public double UnlockCount4
        {
            get
            {
                return this._UnlockCount4;
            }
            set
            {
                this._UnlockCount4 = value;
            }
        }
    }
}
