// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    
    public class achievetable
    {
        
        public double id;
        
        public string AchieveDatil;
        
        public double Title;
        
        public System.Collections.Generic.List<double> Achieve1;
        
        public System.Collections.Generic.List<double> AchieveCount1;
        
        public System.Collections.Generic.List<double> IconPath;
        
        public double UnlockType1;
        
        public double UnlockCount1;
        
        public double UnlockType2;
        
        public double UnlockCount2;
        
        public double UnlockType3;
        
        public double UnlockCount3;
        
        public double UnlockType4;
        
        public double UnlockCount4;
    }
}
