//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    using SQLite4Unity3d;
    
    
    public class Buff
    {
        
        // buffid
      [PrimaryKey] 
        public double Id {get;set;}
        // buff类型
       public double BuffType {get;set;}
        // 冷却时间（回合）
       public double CD {get;set;}
        // 持续时间（回合）
       public double LifeTime {get;set;}
        // 描述
       public string Des {get;set;}
        // 参数列表 | 字符串类型
       public List<string> Params_StrValue {get;set;}
        // 公式
       public List<string> Params_Expression {get;set;}
        // 参数列表，数值类型(固定数值)
       public List<double> Params_NumValue {get;set;}
        // 显示特效
       public double Effect {get;set;}
    }
}
