//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    using SQLite4Unity3d;
    
    
    public class Hero
    {
        
        // id
      [PrimaryKey] 
        public double Id {get;set;}
        // 名称
       public string Name {get;set;}
        // 级别
       public string Level {get;set;}
        // 星级
       public double StarLevel {get;set;}
        // 下个等级
       public double NextLevel {get;set;}
        // 属性名
       public List<string> AttributeName {get;set;}
        // 属性值
       public List<double> AttributeValue {get;set;}
        // 拥有技能id
       public List<double> Skills {get;set;}
    }
}
