// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    
    
    public class buff : LocalDataBase
    {
        
        private double _BuffType;
        
        private double _CD;
        
        private double _LifeTime;
        
        private string _Des;
        
        private System.Collections.Generic.List<string> _Params_StrValue;
        
        private System.Collections.Generic.List<string> _Params_Expression;
        
        private System.Collections.Generic.List<double> _Params_NumValue;
        
        private double _Effect;
        
        // buff类型
        public double BuffType
        {
            get
            {
                return this._BuffType;
            }
            set
            {
                this._BuffType = value;
            }
        }
        
        // 冷却时间（回合）
        public double CD
        {
            get
            {
                return this._CD;
            }
            set
            {
                this._CD = value;
            }
        }
        
        // 持续时间（回合）
        public double LifeTime
        {
            get
            {
                return this._LifeTime;
            }
            set
            {
                this._LifeTime = value;
            }
        }
        
        // 描述
        public string Des
        {
            get
            {
                return this._Des;
            }
            set
            {
                this._Des = value;
            }
        }
        
        // 参数列表，字符串类型
        public System.Collections.Generic.List<string> Params_StrValue
        {
            get
            {
                return this._Params_StrValue;
            }
            set
            {
                this._Params_StrValue = value;
            }
        }
        
        // 公式
        public System.Collections.Generic.List<string> Params_Expression
        {
            get
            {
                return this._Params_Expression;
            }
            set
            {
                this._Params_Expression = value;
            }
        }
        
        // 参数列表，数值类型(固定数值)
        public System.Collections.Generic.List<double> Params_NumValue
        {
            get
            {
                return this._Params_NumValue;
            }
            set
            {
                this._Params_NumValue = value;
            }
        }
        
        // 显示特效
        public double Effect
        {
            get
            {
                return this._Effect;
            }
            set
            {
                this._Effect = value;
            }
        }
    }
}
