
//------------------------------------------------------------------------------
// <auto-generated>
//    Genera by BDFramework
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.Local
{
    using System;
    using System.Collections.Generic;
    using SQLite4Unity3d;
    
    [Serializable()]
    public class Skill
    {
        
        /// <summary>
        /// 技能
        /// </summary>
        [PrimaryKey]
        public int Id {get;set;}
        /// <summary>
        /// 技能名
        /// </summary>
        public string Name {get;set;}
        /// <summary>
        /// 下一级ID
        /// </summary>
        public int NextLevelID {get;set;}
        /// <summary>
        /// 是否被动技能
        /// </summary>
        public bool IsPassive {get;set;}
        /// <summary>
        /// Buff列表
        /// </summary>
        public int[] Buffs {get;set;}
        /// <summary>
        /// 攻击单位
        /// </summary>
        public int AttackNum {get;set;}
        /// <summary>
        /// 攻击系数
        /// </summary>
        public float[] AttackRatio {get;set;}
        /// <summary>
        /// 攻击次数
        /// </summary>
        public int AttackCount {get;set;}
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon {get;set;}
        /// <summary>
        /// 技能描述
        /// </summary>
        public string Des {get;set;}
        /// <summary>
        /// 特效路径
        /// </summary>
        public string Effect {get;set;}
        /// <summary>
        /// 特效类型
        /// </summary>
        public int EffectType {get;set;}
    }
}