
//------------------------------------------------------------------------------
// <auto-generated>
//    Genera by BDFramework
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.Server
{
    using System;
    using System.Collections.Generic;
    using SQLite4Unity3d;
    
    [Serializable()]
    public class SkillServerLocalTest
    {
        
        /// <summary>
        /// 技能
        /// </summary>
        [PrimaryKey]
        public int Id {get;set;}
        /// <summary>
        /// 服务器字段测试
        /// </summary>
        public string ServerTest {get;set;}
    }
}