namespace BDFramework.Editor.TableData
{
    public class GenCodeTool
    {
        public string CalssContent = @"
//------------------------------------------------------------------------------
// <auto-generated>
//    Genera by BDFramework
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.[NameSpace]
{
    using System;
    using System.Collections.Generic;
    using SQLite4Unity3d;
    
    [Serializable()]
    public class [ClsName]
    {
        [Fields]
    }
}";

        public string FieldContent = @"
        /// <summary>
        /// [Statement]
        /// </summary>
        [Attribute]
        public [Type] [Name] {get;set;}";

        public string FieldContent2 = @"
        /// <summary>
        /// [Statement]
        /// </summary>
        public [Type] [Name] {get;set;}";

        private string clsName = "Noname";

        public GenCodeTool(string clsName)
        {
            this.clsName = clsName;
        }


        private string fieldContents = "";

        /// <summary>
        /// 添加字段
        /// </summary>
        /// <param name="statement">注释</param>
        /// <param name="attribute">属性</param>
        /// <param name="type">类型</param>
        /// <param name="fieldName">字段名</param>
        public void AddField(string statement, string attribute, string type, string fieldName)
        {
            string tempfield = "";
            if (string.IsNullOrEmpty(attribute))
            {
                tempfield = this.FieldContent2;
            }
            else
            {
                tempfield = this.FieldContent;
            }

            tempfield = tempfield.Replace("[Statement]", statement);
            if (!string.IsNullOrEmpty(attribute))
            {
                tempfield = tempfield.Replace("[Attribute]", $"[{attribute}]");
            }

            tempfield = tempfield.Replace("[Type]", type);
            tempfield = tempfield.Replace("[Name]", fieldName);

            this.fieldContents += tempfield;
        }


        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="filePath"></param>
        public string GenClass(string @namespace)
        {
            this.CalssContent = CalssContent.Replace("[ClsName]", clsName) //
                .Replace("[Fields]", fieldContents);
            this.CalssContent = this.CalssContent.Replace("[NameSpace]", @namespace);
            return this.CalssContent;
        }
    }
}